name: Check GameCube Stock (Every 40 Minutes)
permissions:
  contents: write

on:
  schedule:
    - cron: "0,40 * * * *"
  workflow_dispatch:

jobs:
  check_stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-chromedriver@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install selenium
      - name: Run stock checker
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python check_stock_and_notify.py
      - name: Commit and push log
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add logs/
          if ! git diff --cached --quiet; then
            git commit -m "Update stock check log"
            git push
