name: Check GameCube Stock (Every 40 Minutes)
permissions:
  contents: write

on:
  schedule:
    - cron: "0,40 * * * *"
  workflow_dispatch:

jobs:
  check_stock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Chrome for Testing (124)
        run: |
          set -e
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.119/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/
          sudo ln -sf /opt/chrome-linux64/chrome /usr/bin/google-chrome

      - name: Download Chromedriver for Testing (124)
        run: |
          set -e
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/124.0.6367.119/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install selenium

      - name: Run stock checker
        env:
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python check_stock_and_notify.py

      - name: Commit and push log
        run: |
          set -e
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add logs/
          if ! git diff --cached --quiet; then
            git commit -m "Update stock check log"
            git push
          fi
